### ISSUE TITLE
Report multiple spam at once, prefer whole folder

### ISSUE THREAD

**Issue by SerkTX** [justreportit/thunderbird#33]
Maybe I'm overlooking it, I have all my spam sorted into a spam folder, I manually verify no ham snuck in then under HabuL (I didn't realize how far behind my Thunderbird was until yesterday, which led me here) I'd hit a single Report button on the tool bar and all marked junk in the current folder would be packaged off in a single mail.

With Just Report It (Don't get me wrong, I'm VERY thankful someone is keeping the spirit alive!) it lets me right click on the folder and Report It is an option, but clicking it does nothing.

If I highlight multiple message at once and right click "Report It" is an option, however utilizing it just deletes the messages without reporting them.

Relevant settings:
Configuration Mode - Custom (Configured to my quick Spamcop reporting address; utilizing the built in Spamcop feature kept reverting off of Quick mode)
Default Action - Delete it (Changing that to Move it to trash going forward)
And Custom Report Address is quick.SpamCopID@spam.spamcop.net

Just Repot It version is 2.1.0
Thunderbird version is 91.11.0 32-bit version on Windows

Thank you very much!!! LOVE the way this is going, just a few little quirks to work out and it'll be perfect!

**Comment by nicprov** [comment]
@SerkTX Firstly, the "Report It" button unfortunately appears everywhere when you right click instead of just when selecting one/multiple messages (which is the intended purpose), this is a limitation of Thunderbird. I have to admit, this is a little confusing. 

On the flip side, is reporting an entire folder to SpamCop really a desired feature? SpamCop doesn't accept old messages anyways, so unless the entire folder only contains messages from the last 24 hours, most of them will be rejected.

Regarding your second issue, highlighting multiple messages at once and reporting them should work as it is an expected use case. If I test this on my end, I can confirm that this works when selecting "Spam Cop" as the configuration mode, but **not** when selecting "Custom" which is what you did. So this is in fact a bug.

For your third issue, what exactly is the issue when entering your SpamCopID in the Spam Cop configuration menu? There is an option to use quick spamcop instead, you just need to enable it.

**Comment by SerkTX** [comment]
@nicprov  Thank you for your prompt reply and continued efforts on this!
On reporting an entire folder at a time - I might be an outlier, but although it ebbs and flows, I can easily get 25+ spams a day on my main e-mail, I have SpamAssassin tag them and Thunderbird sorts them all into the Junk folder. I then manually look through them to make sure no ham slipped through, then used to just report the whole Junk folder at once, several times a day.
I also have several honey pot e-mail addresses I intentionally put on forums and web sites 15+ years ago that all mail to them is spam, and it gets another 20-30 a day that all go to a dedicated folder.

Glad you were able to verify the 2nd issue is indeed an issue (Well, sorry there's a bug, but glad it wasn't just in my head :) )

For the third issue, if I put in my Spam Cop ID under the Spam Cop Configuration, click the Enable Quick SpamCop option then click Submit, exit the configuration page then go back into the Just Report It configuration page, my SpamCop ID remains, but the "Enable Quick SpamCop" option has been cleared.
I just redid the steps, and I apologize I might have wasted your time on that one, it appears that although the GUI doesn't reflect the option still being selected, in action it is using the Spamcop Quick reporting feature. (And thus I can now report multiple spams at once. :)


Sorry to pile too many things in one issue, but just an observation while troubleshooting this, currently it appears the tool performs the delete/move to trash action the moment Report It button is clicked, not after the report has been sent. It might be an unnecessarily large amount of work to change it to only perform the removal action after the report is confirmed to have been sent, and once I've got it working properly probably won't be an issue any longer, but just wanted to mention that.

Thank you again for keeping it going!

**Comment by nicprov** [comment]
@SerkTX Your use-case does make sense for reporting an entire folder, I'm just not sure how common this would be. I'll tell you what though, when I dive back into the code to fix the highlighted bugs, I'll try to see how much work it entails, if it's an easy fix, I'll add it, otherwise I'll add it to the backlog for now. For the time being, you can easily select all the emails in a given folder (Ctrl + A), then right click and select report it. One thing to keep in mind though, I'm not sure if SpamCop puts a limit for the number of emails reported at the same time.

Regarding the third issue, I confirmed the same thing on my side. The "Enable Quick SpamCop" option remains un-selected. Luckily this is a very small fix, so I will bundle it with the other fix.

One last point, there is no need to apologize for highlighting bugs! I rely on the community to find issues and make the application better for everyone to use :)
