### ISSUE TITLE
File "sent" into a different folder

### ISSUE THREAD

**Issue by forrie** [justreportit/thunderbird#47]
Would it be possible to direct the mailer (ie Thunderbird) to file the "sent" spam report message into different folder?

**Comment by nicprov** [comment]
@forrie Since this add-on simply populates an email compose screen (it adds the recipient, title, message and attachments), this is not something that can be achieved, at least not easily. By default, Thunderbird puts emails that are sent in the "sent" folder, and I don't think there's a way to change this.

To achieve what you want, the add-on would have to scan for emails in the "sent" folder of all your mailboxes and move them one by one. This is far from an ideal thing.

Having said all that, I'm not sure what the use case for this feature even is. If the messages in your "sent" folder really bother you, I'd recommend using another add-on which enables you to quickly move emails to different folders such as [Quick Folder Move](https://addons.thunderbird.net/en-CA/thunderbird/addon/quick-folder-move/?src=search).
